### ISSUE TITLE
Some blocks are see-through although they shouldn't be

### ISSUE THREAD

**Issue by nerdachse** [Inspirateur/riverbed#4] opened 2024-03-25 14:37 UTC
Hey there!

Thanks again for your inspiring work. Checking out the latest commit 18a43df2fcccb02152d179aa40d752b28be2abc3 (https://github.com/Inspirateur/ourcraft/tree/18a43df2fcccb02152d179aa40d752b28be2abc3) I found a small bug.

I didn't investigate too much yet, maybe it's happening at the chunk borders?

![screenshot_25 03 2024-08 12 04](https://github.com/Inspirateur/ourcraft/assets/97800396/ccb31322-3595-4186-8fc6-83cafbe15fd4)
![screenshot_25 03 2024-08 11 56](https://github.com/Inspirateur/ourcraft/assets/97800396/9c9f6d61-51ac-4219-85c7-deb43758425e)

**Comment by Inspirateur** [comment] 2024-03-26 09:27
Yep I saw it too, I'm not sure why this happens, I haven't changed the meshing code much besides using the greedy meshing function from the block-mesh crate (which should be reliable) and compressing the mesh data. 

The bug only seems to occur after a lot of chunks were already meshed (+ it behaves very strangely), so I'm wondering if this is caused by hitting a memory limit ? 

In any case I'll be upgrading this soon to be even more optimized so we'll see if the bug stays (thanks for the issue nonetheless) :+1:

**Comment by Inspirateur** [comment] 2024-04-01 10:52
After some testing I know this is not a memory issue but i still have no idea what causes this... it's probably related to greedy meshing because i'm pretty sure it wasn't there before i implemented greedy meshing

**Comment by Inspirateur** [comment] 2024-04-01 13:58
I have little hope it gets adressed but I put up an issue summing everything I found so far on the block-mesh repo 
https://github.com/bonsairobo/block-mesh-rs/issues/29

**Comment by Inspirateur** [comment] 2024-04-11 11:10
Seems like it will be addressed soon🤞 !

**Comment by Inspirateur** [comment] 2024-04-17 15:13
Good news ! I fixed the main reasons for holes, but i found a completely unrelated second reason that could also produce holes (but more rarely) and I identified the issue. Since they are technically 2 separates issues i'm going to close this one and open another one

**Closed by Inspirateur** 2024-04-17 15:13 UTC
